using System;

namespace OpcRcw.Hda
{
    public enum OPCHDA_AGGREGATE
    {
        OPCHDA_NOAGGREGATE,
        OPCHDA_INTERPOLATIVE,
        OPCHDA_TOTAL,
        OPCHDA_AVERAGE,
        OPCHDA_TIMEAVERAGE,
        OPCHDA_COUNT,
        OPCHDA_STDEV,
        OPCHDA_MINIMUMACTUALTIME,
        OPCHDA_MINIMUM,
        OPCHDA_MAXIMUMACTUALTIME,
        OPCHDA_MAXIMUM,
        OPCHDA_START,
        OPCHDA_END,
        OPCHDA_DELTA,
        OPCHDA_REGSLOPE,
        OPCHDA_REGCONST,
        OPCHDA_REGDEV,
        OPCHDA_VARIANCE,
        OPCHDA_RANGE,
        OPCHDA_DURATIONGOOD,
        OPCHDA_DURATIONBAD,
        OPCHDA_PERCENTGOOD,
        OPCHDA_PERCENTBAD,
        OPCHDA_WORSTQUALITY,
        OPCHDA_ANNOTATIONS
    }
}